/**
 * The messages one named person receives, composed in their language and handed
 * to the port (`AUTH-003/T3`).
 *
 * Two messages share this module because they are one act with two reasons: an
 * invitation and a reset both carry a single-use link to somebody who is not
 * signed in, and building them apart would give two subjects, two expiry
 * sentences and two chances to say something the link does not do.
 *
 * **Transactional, and that word carries a rule.** These are not investor mail:
 * they are the message without which the person cannot get in, so `MAIL-002`'s
 * unsubscribe must never suppress them (`MAIL-002/T3`) and nothing here reads the
 * suppression list. What *does* stop them is the credential being absent or an
 * operator having turned sending off — the first because there is no mailbox to
 * hand a message to, the second because somebody decided so (`CFG-001`) — and
 * both leave the invitation itself created and its link on the admin's screen
 * (`SEC-R05`, `AUTH-003/T7`).
 *
 * **The locale is the account's, not the request's.** An invitation is composed
 * while an admin is on the screen and read by somebody else tomorrow; a reset is
 * composed for a person who is not signed in. `accounts.locale` is where that
 * language lives, and null there means not known rather than English, so the
 * fallback below is a stated choice and not a column's default standing in for
 * one.
 *
 * **One connection per message, deliberately.** `MAIL-001` §3 warns against
 * opening a connection per message, and that warning is about a send to fifty
 * recipients. This is one message to one person, so one connection is the whole
 * send and there is nothing to reuse it for.
 *
 * `DATA-R04` — no tracking pixel and no click wrapper. The link in the body is
 * the link the person opens, which is also why it is written as a bare URL: the
 * HTML half is generated by `compose` from the same text the plain half carries,
 * and a mail client linkifies a bare URL itself. Wrapping it in an anchor would
 * mean a second renderer with its own escaping, for a message whose plain-text
 * half is the one a corporate client shows.
 */

import { getDb } from '../db/index';
import { translatorFor, type MessageValues, type Translator } from '../i18n/catalogue';
import { DEFAULT_LOCALE, type Locale } from '../i18n/locales';
import { log } from '../ops/logger';

import { sendingIsPossible, type MailAvailability } from './availability';
import { compose, type ComposedMessage, type Mailer } from './mailer';
import { failureText } from './send';
import { openSmtpMailer, SmtpUrlError, type MailerSession } from './smtp';

/** Opening the connection, as a parameter so a test drives a send without a mail server. */
export type SessionOpener = (mail: Extract<MailAvailability, { available: true }>['mail']) => MailerSession;

/**
 * What became of one transactional message.
 *
 * `unavailable` is separate from `failed` because the two ask different things of
 * whoever reads them: a missing credential or a switched-off setting is answered
 * by an operator and means nothing was attempted, while a refusal means the
 * message reached a mail server that would not take it. Collapsing them would put
 * "we tried and it bounced" on a screen where nothing was tried.
 */
export type TransactionalOutcome =
  | { readonly state: 'accepted' }
  | { readonly state: 'failed'; readonly error: string }
  | { readonly state: 'unavailable'; readonly reason: string };

/**
 * Handing a composed message to the port, as one seam.
 *
 * The flows that send these messages — an invitation, a resend, a reset — each
 * take this rather than the two parameters below, because what each of them
 * needs to vary in a test is the *outcome*, never the connection. One seam also
 * means a caller cannot accidentally reach past the availability answer and open
 * a connection the check would have refused.
 */
export type Deliver = (addressee: Addressee, message: ComposedMessage) => Promise<TransactionalOutcome>;

/** The application's own delivery: the SMTP adapter, behind the availability answer. */
export const deliverByPort: Deliver = (addressee, message) => deliverTransactional(addressee, message);

/** The person a message is addressed to, as much of them as composing one needs. */
export interface Addressee {
  readonly id: string;
  readonly email: string;
  readonly name: string;
  /** Their language, or null when nobody recorded one — English then, by the fallback below. */
  readonly locale: Locale | null;
}

/** How long each link lasts, in the unit its sentence states it in. */
const INVITATION_DAYS = 7;
const RESET_HOURS = 1;

/**
 * The catalogue to compose in. Null means an admin did not record a language, so
 * English is the answer — stated here once rather than at each call site, and
 * written as a fallback rather than as a column default so that "we do not know"
 * survives in the row (`AUTH-003` §3: the invitee's locale if known and English
 * otherwise).
 */
function localeOf(addressee: Addressee): Locale {
  return addressee.locale ?? DEFAULT_LOCALE;
}

/**
 * Assemble the body from the namespace's own keys, in one order for both
 * messages.
 *
 * The link is its own paragraph so it survives a client that wraps text: a URL
 * broken across two lines by a greeting run together with it is a link that does
 * not work, and this is the one line in the message that has to.
 */
function body(
  t: Translator,
  name: string,
  intro: MessageValues,
  link: string,
  expiry: string | null,
): string {
  const paragraphs = [t('greeting', { name }), t('intro', intro), t('action'), link, expiry, t('ignore'), t('signature')];

  return paragraphs.filter((paragraph): paragraph is string => paragraph !== null).join('\n\n');
}

/** The invitation: who invited them, what the link does, and when it stops working. */
export async function invitationMessage(
  addressee: Addressee,
  inviter: string,
  link: string,
): Promise<ComposedMessage> {
  const t = await translatorFor(localeOf(addressee), 'invitationMail');

  return compose(t('subject'), body(t, addressee.name, { inviter }, link, t('expiry', { days: INVITATION_DAYS })));
}

/**
 * The registration: that they asked for their own access, and the link that both
 * sets a password and settles that the address is theirs (`AUTH-005/T1`).
 *
 * Its own namespace rather than the invitation's, because the invitation's first
 * sentence names the person who sent it and this message has nobody to name. A
 * shared namespace would need that name to become optional, and an optional name
 * in a sentence is a sentence with two readings in twenty languages.
 *
 * Transactional for the same reason the other two are: it is the message without
 * which the person cannot reach the account they just asked for, so `MAIL-002`'s
 * suppression list is not consulted (`MAIL-002/T3`).
 */
export async function registrationMessage(addressee: Addressee, link: string): Promise<ComposedMessage> {
  const t = await translatorFor(localeOf(addressee), 'registrationMail');

  return compose(t('subject'), body(t, addressee.name, {}, link, t('expiry', { days: INVITATION_DAYS })));
}

/**
 * The answer to a registration for an address an account already holds: that one
 * does, that no second was made, and the way in (`AUTH-005/T2`).
 *
 * **This message is what lets the form answer identically either way.** The
 * screen cannot say whether the address was known without becoming the
 * membership test `SEC-R03` refuses, so the difference is moved into a mailbox
 * only the address's own holder can open. Somebody probing addresses learns
 * nothing; the person who actually typed theirs is told what happened.
 *
 * It carries the sign-in page and no token. A link that set a password would be
 * a self-service reset for anybody who knows an address, and re-issuing the
 * invitation an `invited` account is already waiting on would let an anonymous
 * post destroy the link somebody was sent — the denial of access
 * `requestReset`'s narrowing closes from the other side.
 *
 * It carries no expiry, because nothing in it expires: the sign-in page is where
 * it was yesterday. `body` drops the paragraph rather than printing an empty
 * one, so the message reads as written rather than as a template with a hole.
 */
export async function registrationExistsMessage(
  addressee: Addressee,
  signIn: string,
): Promise<ComposedMessage> {
  const t = await translatorFor(localeOf(addressee), 'registrationExistsMail');

  return compose(t('subject'), body(t, addressee.name, {}, signIn, null));
}

/** The reset: that somebody asked, what to do if it was not them, and the hour it lasts. */
export async function resetMessage(addressee: Addressee, link: string): Promise<ComposedMessage> {
  const t = await translatorFor(localeOf(addressee), 'resetMail');

  return compose(t('subject'), body(t, addressee.name, {}, link, t('expiry', { hours: RESET_HOURS })));
}

/**
 * Hand one composed message to the port, recording the attempt as `MAIL-001/T5`
 * records a bulk one: the row is written `queued` before anything leaves, and
 * moved by its own statement afterwards, so a crash in between leaves a record
 * of an attempt whose outcome is unknown rather than no record at all.
 *
 * **No audit row, and that is the design rather than an omission.** The act that
 * caused this message is already in the trail — `account.create` for an
 * invitation, `account.resend` or `account.password_reset_request` for the two an
 * admin starts — and a self-service reset is deliberately not audited
 * (`ADMIN-DEC-03`): the trail holds one account reaching into another's access,
 * and a person asking about their own is neither privileged nor anybody else's. A
 * row written here would also be a row written only when an account exists, with
 * no actor to attribute it to — the existence oracle `SEC-R03` forbids, moved
 * into the trail.
 *
 * The recipient reaches the record as an account id and never as an address
 * (`DATA-R02`); a refusal is scrubbed and capped by the same function the bulk
 * send uses, because an SMTP rejection echoes the address it refused and a TLS
 * failure can echo the credential.
 */
export async function deliverTransactional(
  addressee: Addressee,
  message: ComposedMessage,
  open: SessionOpener = openSmtpMailer,
  availabilityOf: () => Promise<MailAvailability> = sendingIsPossible,
): Promise<TransactionalOutcome> {
  const availability = await availabilityOf();

  if (!availability.available) {
    return { state: 'unavailable', reason: availability.reason };
  }

  let session: MailerSession;
  try {
    session = open(availability.mail);
  } catch (error) {
    // A malformed `SMTP_URL` is an operator's to fix and nothing was attempted,
    // so it answers `unavailable` rather than leaving a `failed` row that reads
    // as a mail server having refused the person.
    if (error instanceof SmtpUrlError) {
      return { state: 'unavailable', reason: error.message };
    }
    throw error;
  }

  try {
    return await attempt(addressee, message, session.mailer);
  } finally {
    session.close();
  }
}

/** The row, the hand-off and the row again — the part that is the same for every message. */
async function attempt(
  addressee: Addressee,
  message: ComposedMessage,
  mailer: Mailer,
): Promise<TransactionalOutcome> {
  const db = getDb();
  const row = await db
    .insertInto('mail_log')
    .values({ account_id: addressee.id, subject: message.subject, kind: 'transactional', state: 'queued' })
    .returning('id')
    .executeTakeFirstOrThrow();

  let receipt;
  try {
    receipt = await mailer.send(addressee.email, message.subject, message.text, message.html);
  } catch (error) {
    const failure = failureText(error);
    await db.updateTable('mail_log').set({ state: 'failed', error: failure }).where('id', '=', row.id).execute();
    log.error('mail.transactional_failed', 'a transactional message was refused', { account_id: addressee.id });

    return { state: 'failed', error: failure };
  }

  await db
    .updateTable('mail_log')
    .set({ state: 'accepted', queue_id: receipt.queueId })
    .where('id', '=', row.id)
    .execute();

  return { state: 'accepted' };
}
